In [8]:
import numpy as np

array = np.random.rand(5,5)
arr_tr = np.zeros((5,5))

for i in range(5):
  for j in range(5):
    arr_tr[j][i]=array[i][j]
np.savetxt('t.txt',arr_tr,fmt="%.f")

print(arr_tr)


[[0.66360674 0.96642699 0.70582006 0.40220498 0.99278344]
 [0.18162441 0.1207305  0.38777843 0.13928862 0.78910523]
 [0.68152371 0.56876106 0.19215765 0.96482271 0.53962446]
 [0.19552466 0.79955731 0.90756061 0.97187706 0.66911794]
 [0.71485303 0.83312438 0.29385054 0.97156481 0.42985339]]


In [9]:
print(array)

[[0.66360674 0.18162441 0.68152371 0.19552466 0.71485303]
 [0.96642699 0.1207305  0.56876106 0.79955731 0.83312438]
 [0.70582006 0.38777843 0.19215765 0.90756061 0.29385054]
 [0.40220498 0.13928862 0.96482271 0.97187706 0.97156481]
 [0.99278344 0.78910523 0.53962446 0.66911794 0.42985339]]
